export const cardsFront = [
    "./assets/Cards/CardsFront/Knight_of_swords.png",
    "./assets/Cards/CardsFront/Six_of_swords.png",
    "./assets/Cards/CardsFront/THE_STAR.png",
    "./assets/Cards/CardsFront/Pgae_of_swords.png",
    "./assets/Cards/CardsFront/Four_of_Pentacles.png",
    "./assets/Cards/CardsFront/The_Lovers.png",
    "./assets/Cards/CardsFront/Seven_of_swords.png",
    "./assets/Cards/CardsFront/Three_of_Wands.png",
    "./assets/Cards/CardsFront/Seven_of_Wands.png",
    "./assets/Cards/CardsFront/Eight_of_Wands.png",
    "./assets/Cards/CardsFront/The_HIEROPHANT.png",
    "./assets/Cards/CardsFront/Nine_of_swords.png",
    "./assets/Cards/CardsFront/Four_of_Wands.png",
    "./assets/Cards/CardsFront/Knight_of_Pentacles.png",
    "./assets/Cards/CardsFront/Queen_of_swords.png",
    "./assets/Cards/CardsFront/Ten_of_swords.png",
    "./assets/Cards/CardsFront/Eight_of_swords.png",
    "./assets/Cards/CardsFront/The_Hanged_Man.png",
    "./assets/Cards/CardsFront/Sun_card.png",
    "./assets/Cards/CardsFront/Ten_of_Pentacles.png",
    "./assets/Cards/CardsFront/Five_of_swords.png",
    "./assets/Cards/CardsFront/The_Moon.png",
    "./assets/Cards/CardsFront/Ace_of_Cups.png",
    "./assets/Cards/CardsFront/Four_of_cups.png",
    "./assets/Cards/CardsFront/King_of_Pentacles.png",
    "./assets/Cards/CardsFront/King_of_Cups.png",
    "./assets/Cards/CardsFront/The_Emperor.png",
    "./assets/Cards/CardsFront/Seven_of_cups.png",
    "./assets/Cards/CardsFront/Two_of_cups.png",
    "./assets/Cards/CardsFront/The_World.png",
    "./assets/Cards/CardsFront/High_Priestest.png",
    "./assets/Cards/CardsFront/Two_of_swords.png",
    "./assets/Cards/CardsFront/Wheel_of_Fortune.png",
    "./assets/Cards/CardsFront/Four_of_swords.png",
    "./assets/Cards/CardsFront/The_Fool.png",
    "./assets/Cards/CardsFront/Ace_of_Wands.png",
    "./assets/Cards/CardsFront/Eight_of_Pentacles.png",
    "./assets/Cards/CardsFront/King_of_swords.png",
    "./assets/Cards/CardsFront/Queen_of_Pentacles.png",
    "./assets/Cards/CardsFront/Five_of_Wands.png",
    "./assets/Cards/CardsFront/Seven_of_Pentacles.png",
    "./assets/Cards/CardsFront/Six_of_Pentacles.png",
    "./assets/Cards/CardsFront/Knight_of_Cups.png",
    "./assets/Cards/CardsFront/Ten_of_cups.png",
    "./assets/Cards/CardsFront/Magicans.png",
    "./assets/Cards/CardsFront/The_Empress.png",
    "./assets/Cards/CardsFront/Six_of_cups.png",
    "./assets/Cards/CardsFront/Ten_of_Wands.png",
    "./assets/Cards/CardsFront/Three_of_Pentacles.png",
    "./assets/Cards/CardsFront/Eight_of_cups.png",
    "./assets/Cards/CardsFront/Five_of_Pentacles.png",
    "./assets/Cards/CardsFront/Queen_of_Cups.png",
    "./assets/Cards/CardsFront/Two_of_Wands.png",
    "./assets/Cards/CardsFront/The_Devil.png",
    "./assets/Cards/CardsFront/The_Hermit.png",
    "./assets/Cards/CardsFront/Strength.png",
    "./assets/Cards/CardsFront/Nine_of_Wands.png",
    "./assets/Cards/CardsFront/Judgement.png",
    "./assets/Cards/CardsFront/Temperance.png",
    "./assets/Cards/CardsFront/Six_of_Wands.png",
    "./assets/Cards/CardsFront/Death.png",
    "./assets/Cards/CardsFront/Justice.png",
    "./assets/Cards/CardsFront/Two_of_Pentacles.png",
    "./assets/Cards/CardsFront/The_Tower.png",
    "./assets/Cards/CardsFront/Three_of_cups.png",
    "./assets/Cards/CardsFront/The_Chariot.png",
    "./assets/Cards/CardsFront/Nine_of_Pentacles.png",
    "./assets/Cards/CardsFront/Five_of_cups.png",
    "./assets/Cards/CardsFront/Ace_of_swords.png",
    "./assets/Cards/CardsFront/Three_of_swords.png",
    "./assets/Cards/CardsFront/Nine_of_cups.png",
    "./assets/Cards/CardsFront/Ace_of_Pentacles.png"
];

export const cardsFrontReversed = [
    "./assets/Cards/CardsFrontReversed/Nine_of_cups_R.png",
    "./assets/Cards/CardsFrontReversed/Queen_of_Cups_R.png",
    "./assets/Cards/CardsFrontReversed/Four_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/Knight_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/The_Emperor_R.png",
    "./assets/Cards/CardsFrontReversed/Page_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Seven_of_cups_R.png",
    "./assets/Cards/CardsFrontReversed/The_Lovers_R.png",
    "./assets/Cards/CardsFrontReversed/Six_of_cups_R.png",
    "./assets/Cards/CardsFrontReversed/Knight_of_Cups_R.png",
    "./assets/Cards/CardsFrontReversed/THE_STAR_R.png",
    "./assets/Cards/CardsFrontReversed/Queen_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/Four_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Four_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/Eight_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Ace_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/The_Devil_R.png",
    "./assets/Cards/CardsFrontReversed/Two_of_cups_R.png",
    "./assets/Cards/CardsFrontReversed/Three_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Magicans_R.png",
    "./assets/Cards/CardsFrontReversed/Wheel_of_Fortune_R.png",
    "./assets/Cards/CardsFrontReversed/Five_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Six_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/Death_R.png",
    "./assets/Cards/CardsFrontReversed/Ace_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/Knight_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/King_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Five_of_cups_R.png",
    "./assets/Cards/CardsFrontReversed/Strength_R.png",
    "./assets/Cards/CardsFrontReversed/Seven_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/Two_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Ten_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/Eight_of_cups_R.png",
    "./assets/Cards/CardsFrontReversed/Ten_of_cups_R.png",
    "./assets/Cards/CardsFrontReversed/Six_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/Five_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/Three_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/High_Priestest_R.png",
    "./assets/Cards/CardsFrontReversed/Queen_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Eight_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/Nine_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/The_HIEROPHANT_R.png",
    "./assets/Cards/CardsFrontReversed/Justice_R.png",
    "./assets/Cards/CardsFrontReversed/Two_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/The_Tower_R.png",
    "./assets/Cards/CardsFrontReversed/Ten_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/Six_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Two_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/Ten_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Nine_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/King_of_Cups_R.png",
    "./assets/Cards/CardsFrontReversed/Sun_card_R.png",
    "./assets/Cards/CardsFrontReversed/Judgement_R.png",
    "./assets/Cards/CardsFrontReversed/Four_of_cups_R.png",
    "./assets/Cards/CardsFrontReversed/Eight_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/King_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/Seven_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/Seven_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/The_Moon_R.png",
    "./assets/Cards/CardsFrontReversed/Ace_of_Cups_R.png",
    "./assets/Cards/CardsFrontReversed/Three_of_cups_R.png",
    "./assets/Cards/CardsFrontReversed/Temperance_R.png",
    "./assets/Cards/CardsFrontReversed/The_Empress_R.png",
    "./assets/Cards/CardsFrontReversed/The_Fool_R.png",
    "./assets/Cards/CardsFrontReversed/Five_of_Pentacles_R.png",
    "./assets/Cards/CardsFrontReversed/Three_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/Nine_of_swords_R.png",
    "./assets/Cards/CardsFrontReversed/The_Hermit_R.png",
    "./assets/Cards/CardsFrontReversed/The_Chariot_R.png",
    "./assets/Cards/CardsFrontReversed/Ace_of_Wands_R.png",
    "./assets/Cards/CardsFrontReversed/The_World_R.png",
    "./assets/Cards/CardsFrontReversed/The_Hanged_Man_R.png",
];

export const cardsMeaning = [
    "./assets/Cards/CardsMeaning/The Emperor A.png",
    "./assets/Cards/CardsMeaning/Death A.png",
    "./assets/Cards/CardsMeaning/Nine of Swords A.png",
    "./assets/Cards/CardsMeaning/Three of Pentacles.png",
    "./assets/Cards/CardsMeaning/Knight of Pentacles A.png",
    "./assets/Cards/CardsMeaning/Six of Wands A.png",
    "./assets/Cards/CardsMeaning/Nine of Cups A.png",
    "./assets/Cards/CardsMeaning/Knight of Wands A.png",
    "./assets/Cards/CardsMeaning/Queen of Cups A.png",
    "./assets/Cards/CardsMeaning/Five of Pentacles.png",
    "./assets/Cards/CardsMeaning/Knight of Cups A.png",
    "./assets/Cards/CardsMeaning/Six of Cups A.png",
    "./assets/Cards/CardsMeaning/The Tower A.png",
    "./assets/Cards/CardsMeaning/Queen of Pentacles A.png",
    "./assets/Cards/CardsMeaning/Strength A.png",
    "./assets/Cards/CardsMeaning/The Lovers A.png",
    "./assets/Cards/CardsMeaning/Seven of Swords A.png",
    "./assets/Cards/CardsMeaning/Seven of Cups A.png",
    "./assets/Cards/CardsMeaning/Group 184.png",
    "./assets/Cards/CardsMeaning/Nine of Pentacles.png",
    "./assets/Cards/CardsMeaning/Queen of Wands A.png",
    "./assets/Cards/CardsMeaning/Ace of Pentacles A.png",
    "./assets/Cards/CardsMeaning/The World A.png",
    "./assets/Cards/CardsMeaning/The Sun A.png",
    "./assets/Cards/CardsMeaning/The Hierophant A.png",
    "./assets/Cards/CardsMeaning/Six of Swords A.png",
    "./assets/Cards/CardsMeaning/Two of Cups A.png",
    "./assets/Cards/CardsMeaning/Eight of Pentacles.png",
    "./assets/Cards/CardsMeaning/Page of Cups A.png",
    "./assets/Cards/CardsMeaning/Four of Wands A.png",
    "./assets/Cards/CardsMeaning/Ten of Swords A.png",
    "./assets/Cards/CardsMeaning/Ten of Cups A.png",
    "./assets/Cards/CardsMeaning/Eight of Cups A.png",
    "./assets/Cards/CardsMeaning/The Star A.png",
    "./assets/Cards/CardsMeaning/Page of Wands A.png",
    "./assets/Cards/CardsMeaning/The High Priestess A.png",
    "./assets/Cards/CardsMeaning/Five of Cups A.png",
    "./assets/Cards/CardsMeaning/Queen of Swords A.png",
    "./assets/Cards/CardsMeaning/Ten of Pentacles A.png",
    "./assets/Cards/CardsMeaning/The Hanged Man A.png",
    "./assets/Cards/CardsMeaning/Six of Pentacles.png",
    "./assets/Cards/CardsMeaning/Seven of Pentacles.png",
    "./assets/Cards/CardsMeaning/King of Wands A.png",
    "./assets/Cards/CardsMeaning/The Devil A.png",
    "./assets/Cards/CardsMeaning/Three of Wands A.png",
    "./assets/Cards/CardsMeaning/Temperance A.png",
    "./assets/Cards/CardsMeaning/Two of Pentacles A.png",
    "./assets/Cards/CardsMeaning/The Moon A.png",
    "./assets/Cards/CardsMeaning/King of Swords A.png",
    "./assets/Cards/CardsMeaning/The Fool A.png",
    "./assets/Cards/CardsMeaning/Two of Swords A.png",
    "./assets/Cards/CardsMeaning/Ace of Wands A.png",
    "./assets/Cards/CardsMeaning/Four of Cups A.png",
    "./assets/Cards/CardsMeaning/Five of Swords A.png",
    "./assets/Cards/CardsMeaning/King of Pentacles A.png",
    "./assets/Cards/CardsMeaning/Page of Pentacles A.png",
    "./assets/Cards/CardsMeaning/Knight of swords A.png",
    "./assets/Cards/CardsMeaning/Seven of Wands A.png",
    "./assets/Cards/CardsMeaning/Three of Swords A.png",
    "./assets/Cards/CardsMeaning/King of Cups A.png",
    "./assets/Cards/CardsMeaning/Four of Swords A.png",
    "./assets/Cards/CardsMeaning/Two of Wands A.png",
    "./assets/Cards/CardsMeaning/Ace of Swords A.png",
    "./assets/Cards/CardsMeaning/The Empress A.png",
    "./assets/Cards/CardsMeaning/Ten of Wands A.png",
    "./assets/Cards/CardsMeaning/Ace of Cups A.png",
    "./assets/Cards/CardsMeaning/Three of Cups A.png",
    "./assets/Cards/CardsMeaning/Wheel of Fortune A.png",
    "./assets/Cards/CardsMeaning/Eight of Wands A.png",
    "./assets/Cards/CardsMeaning/Justice A.png",
    "./assets/Cards/CardsMeaning/Four of Pentacles.png",
    "./assets/Cards/CardsMeaning/Nine of Wands A.png",
    "./assets/Cards/CardsMeaning/Group 165.png",
    "./assets/Cards/CardsMeaning/Page of Swords A.png",
    "./assets/Cards/CardsMeaning/Five of Wands A.png",
    "./assets/Cards/CardsMeaning/The Magician A.png",
    "./assets/Cards/CardsMeaning/The Hermit A.png",
    "./assets/Cards/CardsMeaning/Judgement A.png"
];

